### DISCUSSION TITLE
Access Kafka outside Demo setup

### DISCUSSION THREAD

**Discussion by ghvlg** [HermesGermany/galapagos#5] [Q&A]
How to directly access Kafka made in Demo Setup, from outside, e.g. from separate Docker container running outside of one of Kubernetes clusters made by Demo setup?
Thanks in advance

**Comment by albrechtflo-hg** [comment]
Hi @ghvlg, if you are using Minikube for the Demo setup, the Kafka clusters are exposed using a `NodePort` service. You can run this command to see which ports are used for the Kafkas:

`kubectl get svc --namespace kafka-pseudodev`
`kubectl get svc --namespace kafka-pseudoprod`

Example output:
```
NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                          AGE
kafka-service       NodePort    10.101.212.124   <none>        9092:30635/TCP,29092:32003/TCP   75s
zookeeper-service   ClusterIP   10.110.130.38    <none>        2181/TCP                         105s
```

This means that the Kafka Cluster is reachable using your Minikube's host IP (e.g. 192.168.56.101 when running in a VM, or 127.0.0.1 when running on localhost) and port **30635** for SSL, or 32003 for PLAINTEXT connection (note that PLAINTEXT may not work, as the Kafka is configured to get client authentication from a client SSL certificate).

So you could use e.g. `192.168.56.101:30635` as your "bootstrap servers" property.

An example Spring Boot config file can be downloaded from your running Galapagos. You will need to do the following actions and adjustments:

* Download the truststore from the running Galapagos demo (on Dashboard page)
* Create and download a certificate and private key for your application (choose any of the Demo applications) in Galapagos
* Edit the Spring Boot config to use your downloaded certificate file

As the server certificate of the Kafka broker will most likely not match the correct (used) IP address, you should disable hostname verification, which can be added to the Spring Boot config. The final config may look like this:

```yaml
spring:
  kafka:
    bootstrap-servers: "192.168.56.101:30635"
    ssl:
      trust-store-location: file:./kafka-truststore.jks
      trust-store-password: changeit
      trust-store-type: PKCS12
      key-store-location: file:./aramis_devtest.p12
      key-store-password: changeit
      key-store-type: PKCS12
      protocol: SSL
    properties:
      security.protocol: SSL
      # required for local Kafka server
      ssl.endpoint.identification.algorithm: ""
```

Two example applications (one for producer, and one for consumer) will be added to the HermesGermany workspace soon. There, you will only have to add the mentioned files (truststore and keystore) and set correct bootstrap servers.

Hope that helps!
Florian
